;-------------------------------------------------------------------------------
; basic function references
;-------------------------------------------------------------------------------

func name()() {

	this.is.a.compound.name()()
	simple_name()()
	name1(input.parameters, 123, "this is a string"(123, dfjkdf))()
	name2()(output.parameters, must, be, coupound.names)
	name3(123, 50+2/6, "string")(some, names) 
}
