#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct {
    const char** str;
    size_t cap;
    size_t len;
} strlist_t;

strlist_t* strings;

const char* _strdup(const char* str) {

    size_t len = strlen(str)+1;
    char* s = malloc(len);
    memcpy(s, str, len);
    return s;
}

void create_str_list() {

    strings = malloc(sizeof(strlist_t));
    strings->cap = 0x01 << 8;
    strings->len = 0;
    strings->str = malloc(strings->cap*sizeof(strlist_t*));
}

void destroy_str_list() {

    for(size_t i = 0; i < strings->len; i++)
        free((void*)strings->str[i]);
    free(strings->str);
    free(strings);
}

void add_str_list(const char* str) {

    if(strings->len+1 > strings->cap) {
        strings->cap <<= 1;
        strings->str = realloc(strings->str, strings->cap);
    }

    strings->str[strings->len] = _strdup(str);
    strings->len++;
}

void read_str_list(FILE* fp) {

    char buffer[128];
    char* result;

    while(NULL != (result = fgets(buffer, sizeof(buffer), fp))) {
        if(strlen(result) > 2) {
            add_str_list(result);
        }
    }
}

void emit_str_list(FILE* fp) {

    fprintf(fp, "// This file is automatically generated by make process\n");
    //fprintf(fp, "\n#include \"token.h\"\n\n");
    fprintf(fp, "struct _keyword {\n");
    fprintf(fp, "    const char* str;\n");
    fprintf(fp, "    token_type type;\n");
    fprintf(fp, "} _keyword_list[] = {\n");

    for(size_t i = 0; i < strings->len; i++)
        fprintf(fp, "%s", strings->str[i]);

    fprintf(fp, "};\n\n");
    fprintf(fp, "#define KW_LIST_LEN ((sizeof(_keyword_list)/sizeof(struct _keyword))-1)\n\n");
}

void sort_str_list() {

    size_t flag = 1;

    while(flag) {
        flag = 0;
        for(size_t i = 0; i < strings->len-1; i++) {
            const char* tmp;
            if(0 < strcmp(strings->str[i], strings->str[i+1])) {
                tmp = strings->str[i];
                strings->str[i] = strings->str[i+1];
                strings->str[i+1] = tmp;
                flag++;
            }
        }
    }
}

int main() {

    FILE* inf = fopen("kw.txt", "r");
    FILE* outf = fopen("keywords.h", "w");

    create_str_list();

    read_str_list(inf);
    fclose(inf);

    sort_str_list();

    emit_str_list(outf);
    fclose(outf);

    destroy_str_list();

    return 0;
}
