;------------------------------------------------------------------------------
; The type name production is part of the literal type name with the 
; addition of a compound name, which is tested elsewhere.
;
;   type_name
;       = literal_type_name
;       / compound_name
;
;------------------------------------------------------------------------------

var this.is.a.compound.name some_name
const var this.is.a.compound.name some_name

