;-------------------------------------------------------------------------------
; Simple test to verify that either a sstrg or a dstrg is recognized
;-------------------------------------------------------------------------------

var string some_name = 'this is a string'
var string some_name = "this is a formatted string"
var string some_name = "this is a formatted string"()
var string some_name = "this is a formatted string"(1,2,3)
